# Generated by Django 4.2.16 on 2024-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_credits_course_maximum_capacity_and_more'),
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='courses.course'),
        ),
    ]
