# Dockerfile inside docker/
FROM python:3.9-slim

WORKDIR /usr/src/app

# Copy requirements.txt from the docker/ folder into the container
COPY requirements.txt . 

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
