# Generated by Django 4.2.16 on 2024-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='availability',
            field=models.CharField(max_length=50),
        ),
    ]
