name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: lms_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d lms_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        env:
          DATABASE_URL: postgres://admin:admin@localhost:5432/lms_db
        run: |
          python manage.py migrate

      - name: Run Tests
        env:
          DATABASE_URL: postgres://admin:admin@localhost:5432/lms_db
        run: |
          pytest --maxfail=1 --disable-warnings
